// FULLY GENERATED by Chat-gpt, so if something does not match constribution is welcome!

pub struct KnownDevice {
    pub vid: u16,
    pub pid: u16,
    pub name: &'static str,
}

pub static DEVICE_DATABASE: &[KnownDevice] = &[
    // --- OFFICIAL ARDUINO BOARDS ---
    KnownDevice {
        vid: 0x2341,
        pid: 0x0043,
        name: "Arduino Uno R3",
    },
    KnownDevice {
        vid: 0x2341,
        pid: 0x0001,
        name: "Arduino Uno R3 (Old Bootloader)",
    },
    KnownDevice {
        vid: 0x2341,
        pid: 0x0010,
        name: "Arduino Mega 2560",
    },
    KnownDevice {
        vid: 0x2341,
        pid: 0x0042,
        name: "Arduino Mega 2560 R3",
    },
    KnownDevice {
        vid: 0x2341,
        pid: 0x0036,
        name: "Arduino Leonardo",
    },
    KnownDevice {
        vid: 0x2341,
        pid: 0x003d,
        name: "Arduino Due",
    },
    KnownDevice {
        vid: 0x2341,
        pid: 0x0037,
        name: "Arduino Micro",
    },
    KnownDevice {
        vid: 0x2341,
        pid: 0x0041,
        name: "Arduino Nano (ATmega328P)",
    },
    KnownDevice {
        vid: 0x2341,
        pid: 0x804d,
        name: "Arduino Zero",
    },
    KnownDevice {
        vid: 0x2341,
        pid: 0x0058,
        name: "Arduino Nano Every",
    },
    KnownDevice {
        vid: 0x2341,
        pid: 0x005a,
        name: "Arduino Nano 33 IoT",
    },
    KnownDevice {
        vid: 0x2341,
        pid: 0x005e,
        name: "Arduino Nano 33 BLE",
    },
    // --- RASPBERRY PI SILICON ---
    KnownDevice {
        vid: 0x2e8a,
        pid: 0x000a,
        name: "Raspberry Pi Pico (RP2040)",
    },
    KnownDevice {
        vid: 0x2e8a,
        pid: 0x0009,
        name: "Raspberry Pi Pico Bootloader Mode (RP2040)",
    },
    KnownDevice {
        vid: 0x2e8a,
        pid: 0x0003,
        name: "Raspberry Pi Pico W",
    },
    KnownDevice {
        vid: 0x2e8a,
        pid: 0x000f,
        name: "Raspberry Pi Pico 2 (RP2350)",
    },
    // --- TEENSY (PJRC) BOARDS ---
    KnownDevice {
        vid: 0x16c0,
        pid: 0x0483,
        name: "Teensy 4.0 / 4.1 / MicroMod",
    },
    KnownDevice {
        vid: 0x16c0,
        pid: 0x0478,
        name: "Teensy Bootloader Mode",
    },
    KnownDevice {
        vid: 0x16c0,
        pid: 0x0480,
        name: "Teensy 3.X",
    },
    // --- ADAFRUIT & OTHER EXPRESSIF/SAMD BOARDS ---
    KnownDevice {
        vid: 0x239a,
        pid: 0x801b,
        name: "Adafruit ItsyBitsy M4",
    },
    KnownDevice {
        vid: 0x239a,
        pid: 0x8022,
        name: "Adafruit Feather M4",
    },
    KnownDevice {
        vid: 0x239a,
        pid: 0x80cb,
        name: "Adafruit QT Py RP2040",
    },
    KnownDevice {
        vid: 0x303a,
        pid: 0x1001,
        name: "Espressif ESP32-S3 USB-OTG",
    },
    KnownDevice {
        vid: 0x303a,
        pid: 0x4001,
        name: "Espressif ESP32-C3 USB JTAG/Serial",
    },
    // --- WCH CHIPS (The ubiquitous cheap clone processors) ---
    KnownDevice {
        vid: 0x1a86,
        pid: 0x7523,
        name: "CH340 USB-to-Serial (Common Chinese Arduino Clone)",
    },
    KnownDevice {
        vid: 0x1a86,
        pid: 0x5523,
        name: "CH341 USB-to-Serial / Parallel Adapter",
    },
    KnownDevice {
        vid: 0x1a86,
        pid: 0x55d4,
        name: "CH343 High-Speed USB-to-UART Bridge",
    },
    // --- SILICON LABS CHIPS (Industry Standard ESP32/NodeMCU Bridges) ---
    KnownDevice {
        vid: 0x10c4,
        pid: 0xea60,
        name: "Silicon Labs CP210x USB-to-UART Bridge (ESP32/NodeMCU)",
    },
    KnownDevice {
        vid: 0x10c4,
        pid: 0xea70,
        name: "Silicon Labs CP2105 Dual USB-to-UART Bridge",
    },
    // --- FTDI CHIPS (High-End Prototyping & Older Hardware) ---
    KnownDevice {
        vid: 0x0403,
        pid: 0x6001,
        name: "FTDI FT232R USB-to-UART (SparkFun / Nano Clone)",
    },
    KnownDevice {
        vid: 0x0403,
        pid: 0x6010,
        name: "FTDI FT2232H Dual High-Speed UART",
    },
    KnownDevice {
        vid: 0x0403,
        pid: 0x6014,
        name: "FTDI FT232H Single Channel High-Speed UART",
    },
    // --- PROLIFIC & OTHER INTERFACES ---
    KnownDevice {
        vid: 0x067b,
        pid: 0x2303,
        name: "Prolific PL2303 USB-to-Serial",
    },
    KnownDevice {
        vid: 0x1d50,
        pid: 0x6018,
        name: "Black Magic Probe (JTAG/SWD Debugger)",
    },
];

pub fn find_device(vid: u16, pid: u16) -> Option<&'static str> {
    DEVICE_DATABASE
        .iter()
        .find(|device| device.vid == vid && device.pid == pid)
        .map(|device| device.name)
}
